#ifndef DEVRTOSCONFIG_H

#define DEVRTOSCONFIG_H


#define DEVRTOS_MAX_TASKS 10
#define DEVRTOS_MAX_QUEUES 10
#define DEVRTOS_MAX_SEMAPHORES 10
#define DEVRTOS_MAX_EVENTS 10
#define DEVRTOS_MAX_TIMERS 10
#define DEVRTOS_MAX_PRIORITY_LEVELS 10

#endif